use_frameworks!

platform :ios, '10.0'

target 'QLDevTool_Example' do
  pod 'QLDevTool', :path => '../'

  target 'QLDevTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
